In [1]:
# HOW TO HANDLE JSON DATA
import pandas as pd
import json
import parse_json

In [2]:
# Open json data
with open("Leagues of Legends/champion_info_2.json", "r+") as f:
    json_data = json.load(f)
champion = pd.DataFrame(json_data)
champion.reset_index(inplace=True)
champion.rename(columns={"index": "name"}, inplace=True)
champion.head()

,name,type,version,data
0,Aatrox,champion,7.18.1,"{'tags': ['Fighter', 'Tank'], 'title': 'the Da..."
1,Ahri,champion,7.18.1,"{'tags': ['Mage', 'Assassin'], 'title': 'the N..."
2,Akali,champion,7.18.1,"{'tags': ['Assassin'], 'title': 'the Fist of S..."
3,Alistar,champion,7.18.1,"{'tags': ['Tank', 'Support'], 'title': 'the Mi..."
4,Amumu,champion,7.18.1,"{'tags': ['Tank', 'Mage'], 'title': 'the Sad M..."

In [3]:
# Convert the json data to DataFrame
first_row_data = champion.data[0]
champ_data = pd.DataFrame(first_row_data)
for i in range(1, champion.shape[0]):
    champ_data = champ_data.append(pd.DataFrame(champion.data[i]))
champ_data = pd.DataFrame(champ_data.groupby(['title', 'id', 'name', 'key'])['tags'].apply(lambda x: "%s" % ', '.join(x)))
champ_data.reset_index(inplace=True)
champ_merge = pd.merge(champion, champ_data, how="left", on="name")
champ_merge.head()

,name,type,version,data,title,id,key,tags
0,Aatrox,champion,7.18.1,"{'tags': ['Fighter', 'Tank'], 'title': 'the Da...",the Darkin Blade,266.0,Aatrox,"Fighter, Tank"
1,Ahri,champion,7.18.1,"{'tags': ['Mage', 'Assassin'], 'title': 'the N...",the Nine-Tailed Fox,103.0,Ahri,"Mage, Assassin"
2,Akali,champion,7.18.1,"{'tags': ['Assassin'], 'title': 'the Fist of S...",the Fist of Shadow,84.0,Akali,Assassin
3,Alistar,champion,7.18.1,"{'tags': ['Tank', 'Support'], 'title': 'the Mi...",the Minotaur,12.0,Alistar,"Tank, Support"
4,Amumu,champion,7.18.1,"{'tags': ['Tank', 'Mage'], 'title': 'the Sad M...",the Sad Mummy,32.0,Amumu,"Tank, Mage"

In [4]:
# General method to parse json and add data to the dataframe
champion = parse_json.parse_json(champion, 'data')
champion.head()

,name,type,version,data,tags,key,id,title
0,Aatrox,champion,7.18.1,"{'tags': ['Fighter', 'Tank'], 'title': 'the Da...","[Fighter, Tank]",Aatrox,266,the Darkin Blade
1,Ahri,champion,7.18.1,"{'tags': ['Mage', 'Assassin'], 'title': 'the N...","[Mage, Assassin]",Ahri,103,the Nine-Tailed Fox
2,Akali,champion,7.18.1,"{'tags': ['Assassin'], 'title': 'the Fist of S...",[Assassin],Akali,84,the Fist of Shadow
3,Alistar,champion,7.18.1,"{'tags': ['Tank', 'Support'], 'title': 'the Mi...","[Tank, Support]",Alistar,12,the Minotaur
4,Amumu,champion,7.18.1,"{'tags': ['Tank', 'Mage'], 'title': 'the Sad M...","[Tank, Mage]",Amumu,32,the Sad Mummy